### ISSUE TITLE
Error #13: Assertion failure at kmp_dispatch.cpp(2430)

### ISSUE THREAD

**Issue by Profetorum** [BoringBoredom/Linpack-Extended#1]
Can't get Linpack Extended to work on Win11 (build 22631) .

Error:
https://imgur.com/a/vkrsMae

Video:
https://streamable.com/2a6ze6

Reproduceable consistently run to run.
Requirements are met.

It isn't most likely a stability issue since i can basically run with no issues the standard Linpack Xtreme test with the same config (39984/39984 with 1 or 4 KB data alignment).

**Comment by BoringBoredom** [comment]
This might be related to Intel's `libiomp5md.dll` file.
Can you try deleting this line?
https://github.com/BoringBoredom/Linpack-Extended/blob/664a61b934e41bb78e7573b6f8cc32b766844770/dependencies/linpack.js#L66

**Comment by Profetorum** [comment]
> This might be related to Intel's `libiomp5md.dll` file. Can you try deleting this line?
> 
> https://github.com/BoringBoredom/Linpack-Extended/blob/664a61b934e41bb78e7573b6f8cc32b766844770/dependencies/linpack.js#L66

It's working, thanks!

![image](https://github.com/BoringBoredom/Linpack-Extended/assets/92865889/ac0c9765-9cd0-48f8-9f4b-4a71b7ce0ac1)

**Comment by BoringBoredom** [comment]
@Profetorum Can you please try the latest version?

**Comment by Profetorum** [comment]
> @Profetorum Can you please try the latest version?

Sorry for the late response.
For me, the new version doesn't start, it's stuck
![image](https://github.com/BoringBoredom/Linpack-Extended/assets/92865889/5448e3b8-4d40-4b00-83d4-9c11c105d05a)

**Comment by BoringBoredom** [comment]
Is that with or without line 66?

**Comment by Profetorum** [comment]
> Is that with or without line 66?

With line 66, it's just the new version downloaded and extracted

**Comment by BoringBoredom** [comment]
https://github.com/BoringBoredom/Linpack-Extended/issues/2#issuecomment-2054642139
