### ISSUE TITLE
Linpack calculation does not start

### ISSUE THREAD

**Issue by Weissrolf** [BoringBoredom/Linpack-Extended#2]
Hello. While the last version fixed the assertion error it causes Linpack not to start calculating anymore. After the terminal outputs this information there is no CPU load happening and the batch file seems to hang until manually stopped.

```
Start time: 12:21
Time to run: 60 minutes
Problem size: 39984
Leading dimension: 39984
Alignment value: 4
Residual checks: ON
```

**Comment by BoringBoredom** [comment]
https://github.com/BoringBoredom/Linpack-Extended/commit/ff66532d6414f5adaf68a2c58b60d92a1766277e

**Comment by Weissrolf** [comment]
Thanks. Unfortunately back to "OMP: Error #13: Assertion failure at kmp_dispatch.cpp(2430)." error after the fix.

**Comment by Weissrolf** [comment]
I commented out line 66 and now it's working without assertion.

**Comment by BoringBoredom** [comment]
The latest Linpack package doesn't work at all, since the 64-bit `libiomp5md.dll` is missing entirely. The previous one works for me without any OMP errors, but I made the KMP_AFFINITY env variable a config option for people with issues: https://github.com/BoringBoredom/Linpack-Extended?tab=readme-ov-file#workarounds

**Comment by BoringBoredom** [comment]
@Weissrolf @Profetorum Does the latest version work for you without any workarounds?

**Comment by Weissrolf** [comment]
@BoringBoredom Yes, the new version can be run without having to change the KMP affinity setting. This also means that it runs at full speed then (Gflops + Vcore droop).

It is falsely - according to Virustotal - flagged as trojan by Defender, though.

**Comment by BoringBoredom** [comment]
> It is falsely - according to Virustotal - flagged as trojan by Defender, though.

Huh? Are you sure you uploaded the correct files?  
https://www.virustotal.com/gui/file/5eafa157cd2553e1b0e81a4efeaecc1809881c2957f5878e1bc218b2c7726c32/detection

**Comment by Weissrolf** [comment]
I meant that Defender flags the file as Trojan, but Virustotal reveals that it is a "falsely flagged" by Defender, aka not positive in Virustotal, but positive in Defender. Sorry for the confusing sentence.
